/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/U9GmGkt6Zvd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Home() {
  const [activeTab, setActiveTab] = useState("civil")
  return (
    (<div className="flex flex-col h-full">
      <header
        className="bg-background border-b px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <BotIcon className="w-6 h-6" />
            <span className="text-lg font-semibold">RiskG</span>
          </Link>
        </div>
        <nav className="flex items-center gap-6">
          <button
            className={`px-4 py-2 rounded-md transition-colors ${
              activeTab === "civil" ? "bg-primary text-primary-foreground" : "hover:bg-muted"
            }`}
            onClick={() => setActiveTab("civil")}>
            Civil
          </button>
          <button
            className={`px-4 py-2 rounded-md transition-colors ${
              activeTab === "market" ? "bg-primary text-primary-foreground" : "hover:bg-muted"
            }`}
            onClick={() => setActiveTab("market")}>
            Market
          </button>
          <button
            className={`px-4 py-2 rounded-md transition-colors ${
              activeTab === "operational" ? "bg-primary text-primary-foreground" : "hover:bg-muted"
            }`}
            onClick={() => setActiveTab("operational")}>
            Operational
          </button>
        </nav>
      </header>
      <main className="flex-1 overflow-auto">
        {activeTab === "civil" && (
          <div className="p-6 flex flex-col h-full">
            <div className="flex-1 overflow-auto">
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>YO</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">You</div>
                  <div className="prose text-muted-foreground">
                    <p>What are the key considerations for urban planning and development in a growing city?</p>
                  </div>
                </div>
              </div>
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>✨</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">AI Assistant</div>
                  <div className="prose text-muted-foreground">
                    <p>Some key considerations for urban planning and development in a growing city include:</p>
                    <ul>
                      <li>
                        Sustainable infrastructure: Ensuring the city has efficient transportation, energy, and water
                        systems that can support the growing population.
                      </li>
                      <li>
                        Affordable housing: Developing a mix of housing options, including affordable units, to
                        accommodate people of different income levels.
                      </li>
                      <li>
                        Green spaces and public amenities: Incorporating parks, recreational areas, and other public
                        spaces to improve quality of life.
                      </li>
                      <li>
                        Disaster preparedness: Planning for potential natural disasters and implementing measures to
                        mitigate their impact.
                      </li>
                      <li>
                        Inclusive development: Ensuring that urban planning and development consider the needs of all
                        community members, including marginalized groups.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="max-w-2xl w-full sticky bottom-0 mx-auto py-2 flex flex-col gap-1.5 px-4 bg-background">
              <div className="relative">
                <Textarea
                  placeholder="Message AI Assistant..."
                  name="message"
                  id="message"
                  rows={1}
                  className="min-h-[48px] rounded-2xl resize-none p-4 border border-neutral-400 shadow-sm pr-16" />
                <Button
                  type="submit"
                  size="icon"
                  className="absolute w-8 h-8 top-3 right-3"
                  disabled>
                  <ArrowUpIcon className="w-4 h-4" />
                  <span className="sr-only">Send</span>
                </Button>
              </div>
              <p className="text-xs font-medium text-center text-neutral-700">
                The AI assistant may make mistakes. Please verify important information.
              </p>
            </div>
          </div>
        )}
        {activeTab === "market" && (
          <div className="p-6 flex flex-col h-full">
            <div className="flex-1 overflow-auto">
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>YO</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">You</div>
                  <div className="prose text-muted-foreground">
                    <p>
                      Can you provide an overview of the current market trends and opportunities in the technology
                      sector?
                    </p>
                  </div>
                </div>
              </div>
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>✨</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">AI Assistant</div>
                  <div className="prose text-muted-foreground">
                    <p>Here's an overview of some key market trends and opportunities in the technology sector:</p>
                    <ul>
                      <li>
                        Cloud computing: The continued growth and adoption of cloud-based services, including
                        infrastructure-as-a-service (IaaS), platform-as-a-service (PaaS), and software-as-a-service
                        (SaaS).
                      </li>
                      <li>
                        Artificial Intelligence (AI) and Machine Learning (ML): Increasing demand for AI and ML-powered
                        solutions across various industries, such as healthcare, finance, and e-commerce.
                      </li>
                      <li>
                        Internet of Things (IoT): The proliferation of connected devices and the growing need for
                        IoT-based solutions in areas like smart homes, smart cities, and industrial automation.
                      </li>
                      <li>
                        Cybersecurity: Rising concerns about data breaches and the need for robust cybersecurity
                        measures, creating opportunities in areas like network security, endpoint protection, and
                        identity management.
                      </li>
                      <li>
                        5G and next-generation wireless technologies: The rollout of 5G and the potential for innovative
                        applications and services that leverage the increased speed and bandwidth.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="max-w-2xl w-full sticky bottom-0 mx-auto py-2 flex flex-col gap-1.5 px-4 bg-background">
              <div className="relative">
                <Textarea
                  placeholder="Message AI Assistant..."
                  name="message"
                  id="message"
                  rows={1}
                  className="min-h-[48px] rounded-2xl resize-none p-4 border border-neutral-400 shadow-sm pr-16" />
                <Button
                  type="submit"
                  size="icon"
                  className="absolute w-8 h-8 top-3 right-3"
                  disabled>
                  <ArrowUpIcon className="w-4 h-4" />
                  <span className="sr-only">Send</span>
                </Button>
              </div>
              <p className="text-xs font-medium text-center text-neutral-700">
                The AI assistant may make mistakes. Please verify important information.
              </p>
            </div>
          </div>
        )}
        {activeTab === "operational" && (
          <div className="p-6 flex flex-col h-full">
            <div className="flex-1 overflow-auto">
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>YO</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">You</div>
                  <div className="prose text-muted-foreground">
                    <p>
                      What are some best practices for optimizing operational efficiency in a manufacturing environment?
                    </p>
                  </div>
                </div>
              </div>
              <div className="flex items-start gap-4 mb-4">
                <Avatar className="w-8 h-8 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>✨</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-bold">AI Assistant</div>
                  <div className="prose text-muted-foreground">
                    <p>
                      Here are some best practices for optimizing operational efficiency in a manufacturing environment:
                    </p>
                    <ul>
                      <li>
                        Lean manufacturing: Implementing lean principles to eliminate waste, improve workflow, and
                        increase productivity.
                      </li>
                      <li>
                        Automation and robotics: Leveraging automation and robotic technologies to streamline repetitive
                        tasks and improve consistency.
                      </li>
                      <li>
                        Preventive maintenance: Establishing a comprehensive preventive maintenance program to minimize
                        downtime and extend the lifespan of equipment.
                      </li>
                      <li>
                        Data-driven decision making: Utilizing real-time data and analytics to identify bottlenecks,
                        optimize processes, and make informed decisions.
                      </li>
                      <li>
                        Employee training and engagement: Investing in employee training and fostering a culture of
                        continuous improvement to empower the workforce.
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="max-w-2xl w-full sticky bottom-0 mx-auto py-2 flex flex-col gap-1.5 px-4 bg-background">
              <div className="relative">
                <Textarea
                  placeholder="Message AI Assistant..."
                  name="message"
                  id="message"
                  rows={1}
                  className="min-h-[48px] rounded-2xl resize-none p-4 border border-neutral-400 shadow-sm pr-16" />
                <Button
                  type="submit"
                  size="icon"
                  className="absolute w-8 h-8 top-3 right-3"
                  disabled>
                  <ArrowUpIcon className="w-4 h-4" />
                  <span className="sr-only">Send</span>
                </Button>
              </div>
              <p className="text-xs font-medium text-center text-neutral-700">
                The AI assistant may make mistakes. Please verify important information.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>)
  );
}

function ArrowUpIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>)
  );
}


function BotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
